{
 "title": "Games",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "game",
    "query": {
     "query": "label_values(game_server_players_count,game)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(game_active_servers_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Players",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(game_server_players_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Players In Game",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_server_players_count{locked=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers Running by Game",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(game) (game_active_servers_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Player Count by Game",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(game) (game_server_players_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players In Game by Game",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(game) (game_server_players_count{locked=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Game metrics for $game", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "game" },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_active_servers_count{game=\"$game\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_server_players_count{game=\"$game\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players In Game",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(game_server_players_count{locked=\"true\", game=\"$game\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players Per Server",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(room_number) (game_server_players_count{game=\"$game\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}