apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  namespace: influxdb
spec:
  storageClassName: local-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres
