service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"

persistence:
  enabled: true
  storageClassName: ceph-rbd
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.home.jasongodson.com
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

plugins:
  - grafana-clock-panel
  - marcusolsson-treemap-panel

smtp:
  enabled: true
  host: smtp.gmail.com:587
  existingSecret: grafana-smtp
  fromName: Grafana Alerts

grafana.ini:
  reporting_enabled: false
  smtp:
    enabled: true
    host: smtp.gmail.com:587
    from_name: Grafana Alerts
  security:
    cookie_secure: true
    strict_transport_security: true

testFramework:
  enabled: false

imageRenderer:
  enabled: false