service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"

persistence:
  enabled: true
  storageClassName: ceph-rbd
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.home.jasongodson.com
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-read.monitoring.svc.cluster.local:3100
      access: proxy

plugins:
  - grafana-clock-panel
  - marcusolsson-treemap-panel

testFramework:
  enabled: false

imageRenderer:
  enabled: false