# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Metrics export
influxdb:
  api_version: 2
  ssl: true
  host: <REPLACE_ME>
  port: 8086
  token: <REPLACE_ME>
  organization: <REPLACE_ME>
  bucket: homeassistant
  max_retries: 1