# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.253 
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Metrics export
influxdb:
  api_version: 2
  host: influxdb.home.jasongodson.com
  port: 443
  token: <REPLACE_ME>
  organization: <REPLACE_ME>
  bucket: homeassistant
  max_retries: 1AZÍÍ