apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.home.jasongodson.com`)
      kind: Rule
      services:
        - name: prometheus-server
          port: 80