cluster:
  aggregatorCA:
    crt: REDACTED_BASE64
    key: REDACTED_BASE64
  allowSchedulingOnControlPlanes: true
  apiServer:
    admissionControl:
    - configuration:
        apiVersion: pod-security.admission.config.k8s.io/v1alpha1
        defaults:
          audit: restricted
          audit-version: latest
          enforce: baseline
          enforce-version: latest
          warn: restricted
          warn-version: latest
        exemptions:
          namespaces:
          - kube-system
          runtimeClasses: []
          usernames: []
        kind: PodSecurityConfiguration
      name: PodSecurity
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
      - level: Metadata
    certSANs:
    - 192.168.1.30
    - 192.168.1.31
    - 192.168.1.32
    disablePodSecurityPolicy: true
    image: registry.k8s.io/kube-apiserver:v1.36.2
  ca:
    crt: REDACTED_BASE64
    key: REDACTED_BASE64
  clusterName: cluster-private
  controlPlane:
    endpoint: https://192.168.1.250:6443
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.36.2
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
  etcd:
    ca:
      crt: REDACTED_BASE64
      key: REDACTED_BASE64
  extraManifests: []
  id: REDACTED_ID
  inlineManifests: []
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
    - 10.244.0.0/16
    serviceSubnets:
    - 10.96.0.0/12
  proxy:
    image: registry.k8s.io/kube-proxy:v1.36.2
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.36.2
  secret: REDACTED_SECRET
  secretboxEncryptionSecret: REDACTED_SECRET
  serviceAccount:
    key: REDACTED_BASE64
  token: REDACTED_TOKEN
debug: false
machine:
  ca:
    crt: REDACTED_BASE64
    key: REDACTED_BASE64
  certSANs:
  - 192.168.1.30
  - 192.168.1.31
  - 192.168.1.32
  features:
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
    kubePrism:
      enabled: true
      port: 7445
    rbac: true
    stableHostname: true
  install:
    disk: /dev/sda
    image: ghcr.io/siderolabs/installer:v1.13.4
    wipe: false
  kubelet:
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    image: ghcr.io/siderolabs/kubelet:v1.36.2
    nodeIP:
      validSubnets:
      - 192.168.1.30/32
      - 192.168.1.31/32
      - 192.168.1.32/32
  network:
    interfaces:
    - dhcp: false
      interface: ens18
      vip:
        ip: 192.168.1.250
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  token: REDACTED_TOKEN
  type: controlplane
persist: true
version: v1alpha1
