cluster:
  ca:
    crt: REDACTED_BASE64
    key: ""
  clusterName: cluster-private
  controlPlane:
    endpoint: https://192.168.1.250:6443
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
  id: REDACTED_ID
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
    - 10.244.0.0/16
    serviceSubnets:
    - 10.96.0.0/12
  secret: REDACTED_SECRET
  token: REDACTED_TOKEN
debug: false
machine:
  ca:
    crt: REDACTED_BASE64
    key: ""
  certSANs: []
  features:
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
    kubePrism:
      enabled: true
      port: 7445
    rbac: true
    stableHostname: true
  install:
    disk: /dev/sda
    image: ghcr.io/siderolabs/installer:v1.13.4
    wipe: false
  kubelet:
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    image: ghcr.io/siderolabs/kubelet:v1.36.2
    nodeIP:
      validSubnets:
      - 192.168.1.33/32
  network:
    interfaces:
    - dhcp: false
      interface: ens18
    nameservers:
    - 192.168.1.253
  token: REDACTED_TOKEN
  type: worker
persist: true
version: v1alpha1
