global:
  extraArgs:
    - "-config.expand-env=true"

loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  storage_config:
    tsdb_shipper:
      active_index_directory: var/loki/index
      cache_location: var/loki/index_cache
      cache_ttl: 24h
    aws:
      s3: http://192.168.1.252:9000
      s3forcepathstyle: true
      insecure: true
      access_key_id: ${MINIO_ACCESS_KEY}
      secret_access_key: ${MINIO_SECRET_KEY}
  podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault

test:
  enabled: false

lokiCanary:
  enabled: false

ruler:
  enabled: false

write:
  persistence:
    volumeClaimsEnabled: true
    size: 10Gi
    storageClass: ceph-rbd
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  extraEnvFrom:
    - secretRef:
        name: loki-minio-credentials

read:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: loki-minio-credentials
  extraArgs:
    - "-config.expand-env=true"

backend:
  persistence:
    volumeClaimsEnabled: true
    size: 10Gi
    storageClass: ceph-rbd
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: loki-minio-credentials

memcachedExporter:
  enabled: false

resultsCache:
  enabled: false

chunksCache:
  enabled: false

gateway:
  enabled: false

ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
  hosts:
      - loki.home.jasongodson.com