apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`influxdb.home.jasongodson.com`)
      kind: Rule
      services:
        - name: influxdb-influxdb2
          port: 8086