services:
  caddy:
    build: ./Cadddy-Dockerfile
    restart: unless-stopped
    environment:
      - DOMAIN=jasongodson.com
      - ACME_AGREE=true
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/data:/data
      - ./caddy/config:/config