services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
    logging:
      driver: loki
      options:
        loki-url: "https://loki.home.jasongodson.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"