# Secret for Telegraf Proxmox credentials (InfluxDB + Proxmox API)
# Create this secret manually with your actual values
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-influxdb-credentials
  namespace: monitoring
  labels:
    app: telegraf-ssh
type: Opaque
stringData:
  # InfluxDB2 credentials
  influx-token: "your-influxdb-api-token-here"
  influx-org: "your-influxdb-org-id-here"

---
# Secret for Telegraf SSH credentials (VM monitoring)
# Create this secret with: kubectl create secret generic telegraf-ssh-key --from-file=id_rsa=~/.ssh/telegraf_monitoring_key --namespace=monitoring
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-ssh-key
  namespace: monitoring
  labels:
    app: telegraf-ssh
type: Opaque
data:
  # SSH private key (base64 encoded)
  # This will be populated when you run:
  # kubectl create secret generic telegraf-ssh-key --from-file=id_rsa=~/.ssh/telegraf_monitoring_key --namespace=monitoring
