apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-vm-hosts
  namespace: monitoring
data:
  hosts: |
    # One host per line: name:ip
    home-assistant:192.168.1.2
    frigate:192.168.1.3
    media-cloud:192.168.1.4
    cloudflared:192.168.1.19
    ingress-public:192.168.1.20
    ai-tools:192.168.1.248
    minio:192.168.1.252
    ingress-local:192.168.1.253
