services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # For DHCP server
      # - "67:67/udp"
      # - "68:68/tcp"
      # - "68:68/udp"
      - "3000:3000"
      - "8080:80"
  caddy:
    build:
      context: .
      dockerfile: Caddy-Dockerfile
    container_name: caddy
    restart: unless-stopped
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=home.jasongodson.com
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/data:/data
      - ./caddy/config:/config