services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/root_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/root_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=https://prometheus.home.jasongodson.com
      - MINIO_PROMETHEUS_TLS_SKIP_VERIFY=true
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    secrets:
      - root_user
      - root_password
    logging:
      driver: loki
      options:
        loki-url: "https://loki.home.jasongodson.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

secrets:
  root_user:
    file: ./secrets/minio_root_user.txt
  root_password:
    file: ./secrets/minio_root_password.txt