---
# CronJob to ensure Docker authentication is maintained on runner pods
# Runs every hour to refresh Docker login credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-runner-docker-login
  namespace: gitea
spec:
  schedule: "0 * * * *"  # Every hour on the hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: gitea-runner-docker-login
          containers:
          - name: docker-login
            image: alpine/k8s:1.32.9
            command:
              - /bin/sh
              - -c
              - |
                echo "🔐 Starting Docker login refresh for all runner pods..."
                
                # Get all runner pod names
                PODS=$(kubectl get pods -n gitea -l app.kubernetes.io/name=actions-act-runner -o jsonpath='{.items[*].metadata.name}')
                
                for POD in $PODS; do
                  echo "📦 Refreshing Docker login on pod: $POD"
                  
                  # Create .docker directory and config in act-runner container
                  # This is needed because act-runner uses Docker client library which reads from ~/.docker/config.json
                  kubectl exec -n gitea "$POD" -c act-runner -- sh -c \
                    "mkdir -p /root/.docker && echo '{\"auths\":{\"'$REGISTRY_URL'\":{\"auth\":\"'$(echo -n "$REGISTRY_USERNAME:$REGISTRY_PASSWORD" | base64)'\"}} }' > /root/.docker/config.json"
                  
                  if [ $? -eq 0 ]; then
                    echo "✅ Successfully configured Docker auth for $POD"
                  else
                    echo "⚠️  Failed to configure Docker auth for $POD"
                  fi
                done
                
                echo "🎉 Docker login refresh complete!"
            env:
              - name: REGISTRY_URL
                value: "gitea.home.jasongodson.com"
              - name: REGISTRY_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: gitea-docker-registry-creds
                    key: username
              - name: REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: gitea-docker-registry-creds
                    key: password
---
# ServiceAccount for the CronJob
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner-docker-login
  namespace: gitea
---
# Role to allow exec into pods and list pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-runner-docker-login
  namespace: gitea
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-runner-docker-login
  namespace: gitea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-runner-docker-login
subjects:
  - kind: ServiceAccount
    name: gitea-runner-docker-login
    namespace: gitea
